//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChuoiCuaHangCoffee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDH
    {
        public string MADH { get; set; }
        public string MAMON { get; set; }
        public string SIZEMON { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual MON MON { get; set; }
    }
}
