//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChuoiCuaHangCoffee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTMON
    {
        public string MAMON { get; set; }
        public string MANGUYENLIEU { get; set; }
        public Nullable<int> SLNGUYENLIEU { get; set; }
    
        public virtual MON MON { get; set; }
        public virtual NGUYENLIEU NGUYENLIEU { get; set; }
    }
}
