//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChuoiCuaHangCoffee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string IDUSER { get; set; }
        public string USERNAME { get; set; }
        public string USERPASSWORD { get; set; }
        public string HOTEN { get; set; }
        public string EMAIL { get; set; }
        public string CCCD { get; set; }
        public string SODT { get; set; }
        public System.DateTime DOB { get; set; }
        public string DIACHI { get; set; }
        public System.DateTime NGBATDAU { get; set; }
        public Nullable<int> ROLE { get; set; }
        public string IMAGESOURCE { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
