//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChuoiCuaHangCoffee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOUCHER
    {
        public int MAVOUCHER { get; set; }
        public string CODE { get; set; }
        public Nullable<int> DISCOUNT { get; set; }
        public Nullable<System.DateTime> DATEEXPIRED { get; set; }
        public string VOUCHERSTATUS { get; set; }
        public string REASON { get; set; }
    }
}
