CREATE DATABASE QUANLYCOFFEE

USE QUANLYCOFFEE

SET DATEFORMAT DMY;

CREATE TABLE USERS (
	IDUSER VARCHAR(10) PRIMARY KEY,
	USERNAME VARCHAR(50),
	USERPASSWORD VARCHAR(50),
	HOTEN NVARCHAR(100),
	EMAIL VARCHAR(50),
	CCCD VARCHAR(12),
	SODT VARCHAR(10),
	DOB SMALLDATETIME not null,
	DIACHI NVARCHAR(MAX),
	NGBATDAU SMALLDATETIME not null,
	ROLE INT, --1 admin, 2 nhanvien, 3 khachhang
	IMAGESOURCE VARCHAR(MAX)
)

CREATE TABLE CHUCDANH (
    MACD VARCHAR(10) PRIMARY KEY,
    TENCHUCDANH NVARCHAR(MAX),
	LUONGCOBAN MONEY,
    HESOLUONG FLOAT
)

INSERT INTO CHUCDANH (MACD, TENCHUCDANH, LUONGCOBAN, HESOLUONG)
VALUES  ('CD0001', N'Quản lý cửa hàng', 5000000, 8),
		('CD0002', N'Trưởng nhân viên pha chế', 4500000, 6),
		('CD0003', N'Nhân viên pha chế', 4000000, 4),
		('CD0004', N'Nhân viên thu ngân', 4000000, 4),
		('CD0005', N'Nhân viên phục vụ', 3800000, 3);

CREATE TABLE NHANVIEN (
	IDNHANVIEN VARCHAR(10) PRIMARY KEY,
	MACD VARCHAR(10) FOREIGN KEY REFERENCES CHUCDANH(MACD),
	FOREIGN KEY (IDNHANVIEN) REFERENCES USERS(IDUSER)
)


CREATE TABLE NHAPKHO (
    MAPHIEU VARCHAR(10) PRIMARY KEY,
    IDNHANVIEN VARCHAR(10) FOREIGN KEY REFERENCES NHANVIEN(IDNHANVIEN),
    NGNHAPKHO SMALLDATETIME not null,
	TRIGIA MONEY,
)


CREATE TABLE NGUYENLIEU (
    MANGUYENLIEU VARCHAR(10) PRIMARY KEY,
    TENNGUYENLIEU NVARCHAR(50),
	DONVI NVARCHAR(10),
    SOLUONGTRONGKHO INT,
)

CREATE TABLE CTNHAPKHO (
    MAPHIEU VARCHAR(10) FOREIGN KEY REFERENCES NHAPKHO(MAPHIEU),
	MANGUYENLIEU VARCHAR(10) FOREIGN KEY REFERENCES NGUYENLIEU(MANGUYENLIEU),
	SOLUONG INT,
	GIA MONEY,
    PRIMARY KEY (MAPHIEU, MANGUYENLIEU)
)

CREATE TABLE SIZE (
    MASIZE VARCHAR(10) PRIMARY KEY,
    SIZEMON NVARCHAR(10),
    GIABAN MONEY,
	SOLUONG INT,
)

CREATE TABLE MON (
	MAMON VARCHAR(10) PRIMARY KEY,
	MASIZE VARCHAR(10) FOREIGN KEY REFERENCES SIZE(MASIZE) ON DELETE CASCADE,
	TENMON NVARCHAR(100),
	LOAIMON NVARCHAR(20),
	IMAGESOURCE VARCHAR(MAX)
)

CREATE TABLE CTMON (
	MAMON VARCHAR(10) FOREIGN KEY REFERENCES MON(MAMON) on delete cascade,
	MANGUYENLIEU VARCHAR(10) FOREIGN KEY REFERENCES NGUYENLIEU(MANGUYENLIEU),
	SLNGUYENLIEU INT,
	PRIMARY KEY (MAMON, MANGUYENLIEU) 
)

CREATE TABLE KHACHHANG (
	IDKHACHHANG VARCHAR(10) PRIMARY KEY,
	TICHDIEM INT,
	SODONHANG INT,
	HANGTHANHVIEN NVARCHAR(20),
	FOREIGN KEY (IDKHACHHANG) REFERENCES USERS(IDUSER)
)

CREATE TABLE BAN (
	MABAN INT PRIMARY KEY,
	TRANGTHAI NVARCHAR(20)
)

CREATE TABLE DONHANG (
    MADH VARCHAR(10) PRIMARY KEY,
    IDKHACHHANG VARCHAR(10) FOREIGN KEY REFERENCES KHACHHANG(IDKHACHHANG),
    IDNHANVIEN VARCHAR(10) FOREIGN KEY REFERENCES NHANVIEN(IDNHANVIEN),
	MABAN INT FOREIGN KEY REFERENCES BAN(MABAN),
    NGAYDH SMALLDATETIME not null,
    TONGGIATRIDONHANG MONEY,
	DISCOUNT INT,
	TIME_IN SMALLDATETIME,
	TIME_OUT SMALLDATETIME,
    GHICHU NVARCHAR(MAX)
)

CREATE TABLE CTDH (
    MADH VARCHAR(10) FOREIGN KEY REFERENCES DONHANG(MADH),
    MAMON VARCHAR(10) FOREIGN KEY REFERENCES MON(MAMON),
    SIZEMON NVARCHAR(10),
    SOLUONG INT,
    TONGTIEN MONEY,
	PRIMARY KEY (MADH, MAMON)	
)

CREATE TABLE VOUCHER (
	MAVOUCHER INT IDENTITY(1, 1) PRIMARY KEY,
	CODE VARCHAR(12),
	DISCOUNT INT,
	DATEEXPIRED SMALLDATETIME,
	VOUCHERSTATUS NVARCHAR(20),
	REASON NVARCHAR(MAX)
)

-- Thêm một người dùng mới
INSERT INTO USERS (IDUSER, USERNAME, USERPASSWORD, HOTEN, EMAIL, CCCD, SODT, DOB, DIACHI, NGBATDAU, ROLE)
VALUES ('NV0001', 'admin', 'admin', N'Admin', 'admin@gmail.com', '123456789012', '0989898989', '01-01-2003', N'123 Đường ABC, Quận XYZ', '01-01-2023', 1);

-- Thêm một nhân viên mới
INSERT INTO NHANVIEN (IDNHANVIEN, MACD)
VALUES ('NV0001', 'CD0001');
